security.jwt.secret-key=${JWT_SECRET_KEY:3c963f221415d4fc8f3d1b060d4b8e2b83d8df5fbf14d87df2145c1a7e4b2d35}
security.jwt.expiration-time=${JWT_EXPIRATION_TIME:86400000}

spring.datasource.url=jdbc:postgresql://localhost:5432/tododb
spring.datasource.username=postgres
spring.datasource.password=31dec1800

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
